export const AuthActionTypes = {
   USER_SIGNUP_START: 'USER_SIGNUP_START',
   USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
   USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
   USER_LOGIN_START: 'USER_LOGIN_START',
   USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
   USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
   USER_LOGOUT: 'USER_LOGOUT',
   REFRESH_TOKEN_START: 'REFRESH_TOKEN_START',
   REFRESH_TOKEN_ABSENT: 'REFRESH_TOKEN_ABSENT',
   REFRESH_TOKEN_END: 'REFRESH_TOKEN_END',
   SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
}