export const UserActionTypes = {
   SET_CURRENT_USER: 'SET_CURRENT_USER',
   CLEAR_CURRENT_USER: 'CLEAR_CURRENT_USER',
   GET_USER_PROFILE_START: 'GET_USER_PROFILE_START',
   GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
   GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE',
   UPDATE_USER_PROFILE_START: 'UPDATE_USER_PROFILE_START',
   UPDATE_USER_PROFILE_IMAGE_SUCCESS: 'UPDATE_USER_PROFILE_IMAGE_SUCCESS',
   UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
   UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',
   UPDATE_CURRENT_USER_FROM_PROFILE: 'UPDATE_CURRENT_USER_FROM_PROFILE',
}